version: "3.9"

services:
  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: sleepinsight
      MONGO_INITDB_DATABASE: sleepinsight
    volumes:
      - mongo_data:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: sleepinsight
      ME_CONFIG_MONGODB_URL: mongodb://root:sleepinsight@mongo:27017/
      ME_CONFIG_BASICAUTH: false

  frontend:
    image: siailyadev/sleepinsight-frontend:latest
    ports:
      - '5000:80'

  service:
    image: siailyadev/sleepinsight-service:latest
    ports:
      - '3002:3000'
    environment:
      - NODE_ENV=production
      - PORT=3000
      - HOST=localhost
      - CORS_ORIGIN=*
      - MONGODB=mongodb://root:sleepinsight@mongo:27017/
      - ML_SERVICE_URL=http://mlservice:5000

  mlservice:
    image: siailyadev/sleepinsight-mlservice:latest
    ports:
      - '5001:5000'

volumes:
  mongo_data: